version: "2.4"

services:

    mysql:
      build: docker/mysql
      container_name: mysql
      ports:
        - 3306:3306
      volumes:
        - .data-volume:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=asdQWE123
        - MYSQL_DATABASE=maindb
      healthcheck:
        test: "exit 0"

    service:
      build: .
      container_name: service
      ports:
        - 80:80
